### ISSUE TITLE
真是我见过最垃圾的demo架构

### ISSUE THREAD

**Issue by ss2012** [rongcloud/sealmic-android#3]
demo整这么复杂，接入不方便，文档不详细，让别人接入花费大量时间看你们的源码，demo源码根本运行不了，参数配置介绍也不详细，无法运行

**Comment by yangyiRunning** [comment]
@ss2012

1. 这是一个Demo，不是SDK，主要针对语聊房场景，需要在源码的基础上进行二开，阅读源码是绕不开的
2. 业务逻辑和语聊房相关，主要涉及的是一个房间内的语聊场景，具体场景可参见README文档中的时序图和业务描述
3. README文档已详细到每一个包的每一个类的定位和说明，每一个Java关键类中的关键处，也有详细注释
4. 诚如README文档中所说，Demo用到了Android Jetpack的脚手架，请先熟悉Jetpack架构及其各控件的使用

**Comment by fuchangle** [comment]
确实是这样，文档不详细，demo不按照文档步骤写，简直写成了一个项目，真是服了
